# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('uci', 'UCI'), ('postoperatorio', 'Postoperatorio'), ('aislamiento', 'Aislamiento')], default='general', max_length=20)),
                ('capacidad', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Internamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('motivo_ingreso', models.TextField()),
                ('diagnostico_ingreso', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('internado', 'Internado'), ('alta_medica', 'Alta médica'), ('fallecido', 'Fallecido'), ('alta_voluntaria', 'Alta voluntaria')], default='internado', max_length=20)),
                ('dieta', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internamientos', to='hospitalizacion.habitacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internamientos', to='pacientes.paciente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internamiento',
                'verbose_name_plural': 'Internamientos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fc', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado_general', models.CharField(blank=True, max_length=50)),
                ('alimentacion', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField()),
                ('plan', models.TextField(blank=True)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('internamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='hospitalizacion.internamiento')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
