# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('primera_vez', 'Primera vez'), ('control', 'Control'), ('urgencia', 'Urgencia'), ('posoperatorio', 'Postoperatorio'), ('virtual', 'Virtual')], default='primera_vez', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('anamnesis', models.TextField(blank=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fc', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FC (lpm)')),
                ('fr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FR (rpm)')),
                ('mucosas', models.CharField(blank=True, max_length=50)),
                ('linfonodos', models.CharField(blank=True, max_length=100)),
                ('condicion_corporal', models.PositiveSmallIntegerField(blank=True, help_text='1-9', null=True)),
                ('subjetivo', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('evaluacion', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('diagnostico_presuntivo', models.TextField(blank=True)),
                ('diagnostico_definitivo', models.TextField(blank=True)),
                ('pronostico', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConsulta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('primera_vez', 'Primera vez'), ('control', 'Control'), ('urgencia', 'Urgencia'), ('posoperatorio', 'Postoperatorio'), ('virtual', 'Virtual')], default='primera_vez', max_length=20)),
                ('fecha', models.DateTimeField(blank=True, editable=False)),
                ('motivo_consulta', models.TextField()),
                ('anamnesis', models.TextField(blank=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fc', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FC (lpm)')),
                ('fr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='FR (rpm)')),
                ('mucosas', models.CharField(blank=True, max_length=50)),
                ('linfonodos', models.CharField(blank=True, max_length=100)),
                ('condicion_corporal', models.PositiveSmallIntegerField(blank=True, help_text='1-9', null=True)),
                ('subjetivo', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('evaluacion', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('diagnostico_presuntivo', models.TextField(blank=True)),
                ('diagnostico_definitivo', models.TextField(blank=True)),
                ('pronostico', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cita', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agenda.cita')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.paciente')),
                ('veterinario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Consulta',
                'verbose_name_plural': 'historical Consultas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='consultas.consulta')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_nombre', models.CharField(max_length=150)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=80)),
                ('duracion', models.CharField(max_length=80)),
                ('via', models.CharField(max_length=50)),
                ('indicaciones', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='consultas.consulta')),
            ],
        ),
    ]
