# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('bano', 'Baño'), ('corte', 'Corte'), ('bano_corte', 'Baño y corte'), ('guarderia', 'Guardería'), ('completo', 'Servicio completo')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('duracion_horas', models.PositiveSmallIntegerField(default=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='estetica/')),
                ('foto_despues', models.ImageField(blank=True, null=True, upload_to='estetica/')),
                ('completado', models.BooleanField(default=False)),
                ('esteticista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_estetica', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_estetica', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Servicio estético',
                'verbose_name_plural': 'Servicios estéticos',
                'ordering': ['-fecha'],
            },
        ),
    ]
