# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('intervalo_dias', models.PositiveIntegerField(default=365)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.especie')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('dosis', models.CharField(blank=True, max_length=30)),
                ('via', models.CharField(blank=True, max_length=50)),
                ('sitio', models.CharField(blank=True, max_length=80)),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='pacientes.paciente')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacunacion.vacuna')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacunación',
                'verbose_name_plural': 'Vacunaciones',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
