# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salud', 'Certificado de salud'), ('vacunas', 'Certificado de vacunas'), ('viaje', 'Certificado de viaje'), ('esterilizacion', 'Certificado de esterilización'), ('defuncion', 'Certificado de defunción'), ('otro', 'Otro')], max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('contenido', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='pacientes.paciente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
