# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propietarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(default='🐾', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='pacientes.especie')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('especie', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('esterilizado', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/')),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('fallecido', 'Fallecido'), ('dado_baja', 'Dado de baja')], default='activo', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.especie')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='propietarios.propietario')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.raza')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaciente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('microchip', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('esterilizado', models.BooleanField(default=False)),
                ('foto', models.TextField(blank=True, max_length=100, null=True)),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('fallecido', 'Fallecido'), ('dado_baja', 'Dado de baja')], default='activo', max_length=15)),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('especie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.especie')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='propietarios.propietario')),
                ('raza', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.raza')),
            ],
            options={
                'verbose_name': 'historical Paciente',
                'verbose_name_plural': 'historical Pacientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
