# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desparasitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa'), ('ambas', 'Interna y externa')], max_length=10)),
                ('producto_nombre', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=80)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_aplicacion', models.DateField(blank=True, null=True)),
                ('peso_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desparasitaciones', to='pacientes.paciente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desparasitación',
                'verbose_name_plural': 'Desparasitaciones',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
