# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('procedimiento', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_anestesia', models.CharField(choices=[('local', 'Local'), ('general_inh', 'General inhalatoria'), ('general_iny', 'General inyectable'), ('combinada', 'Combinada'), ('ninguna', 'Sin anestesia')], default='general_inh', max_length=15)),
                ('protocolo_anestesico', models.TextField(blank=True)),
                ('hallazgos', models.TextField(blank=True)),
                ('complicaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('complicacion', 'Con complicación')], default='programada', max_length=15)),
                ('cuidados_post', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('anestesista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anestesias', to=settings.AUTH_USER_MODEL)),
                ('cirujano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirugias', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
