# Generated by Django 6.0.5 on 2026-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('nombre_generico', models.CharField(blank=True, max_length=150)),
                ('principio_activo', models.CharField(blank=True, max_length=200)),
                ('concentracion', models.CharField(blank=True, max_length=80)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=80)),
                ('laboratorio', models.CharField(blank=True, max_length=100)),
                ('indicaciones', models.TextField(blank=True)),
                ('contraindicaciones', models.TextField(blank=True)),
                ('dosis_recomendada', models.TextField(blank=True)),
                ('via_administracion', models.CharField(blank=True, max_length=80)),
                ('requiere_receta', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('especies', models.ManyToManyField(blank=True, to='pacientes.especie')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
