# Generated by Django 6.0.5 on 2026-05-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta médica'), ('control', 'Control'), ('vacunacion', 'Vacunación'), ('desparasitacion', 'Desparasitación'), ('cirugia', 'Cirugía'), ('examenes', 'Exámenes'), ('bano_corte', 'Baño y corte'), ('guarderia', 'Guardería'), ('otro', 'Otro')], default='consulta', max_length=20)),
                ('fecha', models.DateTimeField()),
                ('duracion_min', models.PositiveIntegerField(default=30)),
                ('motivo', models.TextField()),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_consulta', 'En consulta'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField(auto_now_add=True)),
                ('hora_atencion', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=5)),
                ('notas_recepcion', models.TextField(blank=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='espera', to='agenda.cita')),
            ],
            options={
                'ordering': ['prioridad', 'hora_llegada'],
            },
        ),
    ]
